

create database identitydb;
;\c identitydb;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Label" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" character varying(30) NOT NULL,
    "HashedPassword" text NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

INSERT INTO "Roles" ("Id", "Label")
VALUES (1, 'admin');
INSERT INTO "Roles" ("Id", "Label")
VALUES (2, 'User');
CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

SELECT setval(
    pg_get_serial_sequence('"Roles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Roles") + 1,
        nextval(pg_get_serial_sequence('"Roles"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230131195257_init', '7.0.2');

COMMIT;
CREATE DATABASE tickets;
\c tickets;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Tickets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    status integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "ClientId" integer NOT NULL,
    "AgentId" integer NULL,
    "OrganisationId" integer NOT NULL,
    CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230131195931_init', '7.0.2');

COMMIT;
CREATE DATABASE "orgs";
\c "orgs";
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Organisations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ManagerId" integer NOT NULL,
    CONSTRAINT "PK_Organisations" PRIMARY KEY ("Id")
);
CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "OrganisationId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Organisations_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

INSERT INTO "Roles" ("Id", "Title")
VALUES (1, 'Client');
INSERT INTO "Roles" ("Id", "Title")
VALUES (2, 'Agent');
CREATE INDEX "IX_Users_OrganisationId" ON "Users" ("OrganisationId");
CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

SELECT setval(
    pg_get_serial_sequence('"Roles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Roles") + 1,
        nextval(pg_get_serial_sequence('"Roles"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230131200306_init', '7.0.2');

COMMIT;
CREATE DATABASE "conversation";
\c "conversation";
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "TicketId" integer NOT NULL,
    "Text" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230131200521_init', '7.0.2');

COMMIT;

