// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketsAPI.DbContext;

#nullable disable

namespace TicketsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230123105438_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketsAPI.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4294),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title1",
                            status = 0
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4308),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title2",
                            status = 0
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4309),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title3",
                            status = 0
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4310),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title4",
                            status = 0
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4312),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title5",
                            status = 0
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4318),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title6",
                            status = 0
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4320),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title7",
                            status = 0
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4322),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title8",
                            status = 0
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4323),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title9",
                            status = 0
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4326),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title10",
                            status = 0
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4328),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title11",
                            status = 0
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4329),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title12",
                            status = 0
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4330),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title13",
                            status = 0
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4331),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title14",
                            status = 0
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4333),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title15",
                            status = 0
                        },
                        new
                        {
                            Id = 16,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4334),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title16",
                            status = 0
                        },
                        new
                        {
                            Id = 17,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4336),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title17",
                            status = 0
                        },
                        new
                        {
                            Id = 18,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4340),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title18",
                            status = 0
                        },
                        new
                        {
                            Id = 19,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4341),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title19",
                            status = 0
                        },
                        new
                        {
                            Id = 20,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4342),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title20",
                            status = 0
                        },
                        new
                        {
                            Id = 21,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4343),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title21",
                            status = 0
                        },
                        new
                        {
                            Id = 22,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4344),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title22",
                            status = 0
                        },
                        new
                        {
                            Id = 23,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4345),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title23",
                            status = 0
                        },
                        new
                        {
                            Id = 24,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4346),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title24",
                            status = 0
                        },
                        new
                        {
                            Id = 25,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4348),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title25",
                            status = 0
                        },
                        new
                        {
                            Id = 26,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4349),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title26",
                            status = 0
                        },
                        new
                        {
                            Id = 27,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4350),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title27",
                            status = 0
                        },
                        new
                        {
                            Id = 28,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4351),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title28",
                            status = 0
                        },
                        new
                        {
                            Id = 29,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4352),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title29",
                            status = 0
                        },
                        new
                        {
                            Id = 30,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4353),
                            Description = "aaaaaaaaaa",
                            OrganisationId = 1,
                            Title = "title30",
                            status = 0
                        },
                        new
                        {
                            Id = 31,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4356),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title31",
                            status = 1
                        },
                        new
                        {
                            Id = 32,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4358),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title32",
                            status = 1
                        },
                        new
                        {
                            Id = 33,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4359),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title33",
                            status = 1
                        },
                        new
                        {
                            Id = 34,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4363),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title34",
                            status = 1
                        },
                        new
                        {
                            Id = 35,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4364),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title35",
                            status = 1
                        },
                        new
                        {
                            Id = 36,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4365),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title36",
                            status = 1
                        },
                        new
                        {
                            Id = 37,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4367),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title37",
                            status = 1
                        },
                        new
                        {
                            Id = 38,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4437),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title38",
                            status = 1
                        },
                        new
                        {
                            Id = 39,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4439),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title39",
                            status = 1
                        },
                        new
                        {
                            Id = 40,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4440),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title40",
                            status = 1
                        },
                        new
                        {
                            Id = 41,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4441),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title41",
                            status = 1
                        },
                        new
                        {
                            Id = 42,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4443),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title42",
                            status = 1
                        },
                        new
                        {
                            Id = 43,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4444),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title43",
                            status = 1
                        },
                        new
                        {
                            Id = 44,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4445),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title44",
                            status = 1
                        },
                        new
                        {
                            Id = 45,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4446),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title45",
                            status = 1
                        },
                        new
                        {
                            Id = 46,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4447),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title46",
                            status = 1
                        },
                        new
                        {
                            Id = 47,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4449),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title47",
                            status = 1
                        },
                        new
                        {
                            Id = 48,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4450),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title48",
                            status = 1
                        },
                        new
                        {
                            Id = 49,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4451),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title49",
                            status = 1
                        },
                        new
                        {
                            Id = 50,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4452),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title50",
                            status = 1
                        },
                        new
                        {
                            Id = 51,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4453),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title51",
                            status = 1
                        },
                        new
                        {
                            Id = 52,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4454),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title52",
                            status = 1
                        },
                        new
                        {
                            Id = 53,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4456),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title53",
                            status = 1
                        },
                        new
                        {
                            Id = 54,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4457),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title54",
                            status = 1
                        },
                        new
                        {
                            Id = 55,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4458),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title55",
                            status = 1
                        },
                        new
                        {
                            Id = 56,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4459),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title56",
                            status = 1
                        },
                        new
                        {
                            Id = 57,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4460),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title57",
                            status = 1
                        },
                        new
                        {
                            Id = 58,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4462),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title58",
                            status = 1
                        },
                        new
                        {
                            Id = 59,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4463),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title59",
                            status = 1
                        },
                        new
                        {
                            Id = 60,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4464),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title60",
                            status = 1
                        },
                        new
                        {
                            Id = 61,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4465),
                            Description = "bbbbbbbb",
                            OrganisationId = 1,
                            Title = "title61",
                            status = 1
                        },
                        new
                        {
                            Id = 62,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4468),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title62",
                            status = 2
                        },
                        new
                        {
                            Id = 63,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4469),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title63",
                            status = 2
                        },
                        new
                        {
                            Id = 64,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4470),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title64",
                            status = 2
                        },
                        new
                        {
                            Id = 65,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4472),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title65",
                            status = 2
                        },
                        new
                        {
                            Id = 66,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4476),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title66",
                            status = 2
                        },
                        new
                        {
                            Id = 67,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4477),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title67",
                            status = 2
                        },
                        new
                        {
                            Id = 68,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4478),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title68",
                            status = 2
                        },
                        new
                        {
                            Id = 69,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4479),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title69",
                            status = 2
                        },
                        new
                        {
                            Id = 70,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4481),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title70",
                            status = 2
                        },
                        new
                        {
                            Id = 71,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4482),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title71",
                            status = 2
                        },
                        new
                        {
                            Id = 72,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4483),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title72",
                            status = 2
                        },
                        new
                        {
                            Id = 73,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4484),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title73",
                            status = 2
                        },
                        new
                        {
                            Id = 74,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4485),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title74",
                            status = 2
                        },
                        new
                        {
                            Id = 75,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4487),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title75",
                            status = 2
                        },
                        new
                        {
                            Id = 76,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4488),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title76",
                            status = 2
                        },
                        new
                        {
                            Id = 77,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4489),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title77",
                            status = 2
                        },
                        new
                        {
                            Id = 78,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4490),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title78",
                            status = 2
                        },
                        new
                        {
                            Id = 79,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4491),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title79",
                            status = 2
                        },
                        new
                        {
                            Id = 80,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4492),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title80",
                            status = 2
                        },
                        new
                        {
                            Id = 81,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4493),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title81",
                            status = 2
                        },
                        new
                        {
                            Id = 82,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4494),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title82",
                            status = 2
                        },
                        new
                        {
                            Id = 83,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4496),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title83",
                            status = 2
                        },
                        new
                        {
                            Id = 84,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4497),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title84",
                            status = 2
                        },
                        new
                        {
                            Id = 85,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4498),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title85",
                            status = 2
                        },
                        new
                        {
                            Id = 86,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4499),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title86",
                            status = 2
                        },
                        new
                        {
                            Id = 87,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4500),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title87",
                            status = 2
                        },
                        new
                        {
                            Id = 88,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4502),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title88",
                            status = 2
                        },
                        new
                        {
                            Id = 89,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4503),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title89",
                            status = 2
                        },
                        new
                        {
                            Id = 90,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4504),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title90",
                            status = 2
                        },
                        new
                        {
                            Id = 91,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4551),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title91",
                            status = 2
                        },
                        new
                        {
                            Id = 92,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 1, 23, 10, 54, 38, 189, DateTimeKind.Utc).AddTicks(4552),
                            Description = "cccccccccc",
                            OrganisationId = 1,
                            Title = "title92",
                            status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
